#!/bin/sh
#
# description: DDVTech RTMP Connector
# processname: DDV_Conn_RTMP

prog="DDV_Conn_RTMP"
fullprog="/usr/bin/DDV_Conn_RTMP"
RETVAL=0

start() {
        echo "Starting $prog"
        $fullprog
        return $?
}

stop() {
        echo "Stopping $prog"
        killall $prog
        return $?
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac

exit $RETVAL
