#!/usr/bin/env python3
"""Embed the compiled JSON translation catalogs into a C++ header.

Rather than one sourcery-generated variable per language plus a hand-written
if-chain in the controller, this emits a single lookup table so adding a
language is a one-line change in lsp/meson.build (or the backend equivalent)
and nothing else.

Usage:
    gen_lang_header.py <out.h> [--prefix NAME] [--no-index] <code>=<native name> [...] -- <code.json> [...]

The specs and the JSON files must be given in the same order.

--prefix distinguishes independent catalog sets that get embedded into the
same binary (e.g. the LSP's frontend catalogs vs. the C++ backend's own
catalogs) so their generated types/variables don't collide if ever included
in the same translation unit. Omit it to get the original unprefixed names
(LangCatalog / langCatalogs / langIndexJson / langIndexJsonLen /
langCatalogCount); `--prefix Backend` instead produces BackendLangCatalog /
backendLangCatalogs / backendLangIndexJson / backendLangIndexJsonLen /
backendLangCatalogCount.

--no-index skips generating the code -> native-name index JSON entirely
(rather than emitting it unused). Only pass this for catalog sets with no
consumer for that index -- e.g. the backend catalogs, which are looked up
internally by a specific resolved language and never listed for a UI
picker, unlike the frontend ones served at /translations/index.json.
"""

import json
import os
import sys


def c_escape(data):
    """Escape a byte string for use in a C string literal, wrapped at 80
    characters per source line for readability (same style as sourcery)."""
    out = []
    line = []
    width = 0
    saw_question = False
    for byte in data:
        if byte == 0x0A:
            chunk = "\\n"
        elif byte == 0x0D:
            chunk = "\\r"
        elif byte == 0x09:
            chunk = "\\t"
        elif byte == 0x5C:
            chunk = "\\\\"
        elif byte == 0x22:
            chunk = '\\"'
        elif byte == 0x3F:
            # Break up "??" so no trigraph can form.
            chunk = '""?' if saw_question else "?"
        elif 32 <= byte <= 126:
            chunk = chr(byte)
        else:
            chunk = f"\\{byte:03o}"
        saw_question = byte == 0x3F
        line.append(chunk)
        width += 1
        if width >= 80:
            out.append(f'"{"".join(line)}"')
            line = []
            width = 0
    if line or not out:
        out.append(f'"{"".join(line)}"')
    return "\n    ".join(out)


def main(argv):
    if "--" not in argv or len(argv) < 3:
        if __doc__:
            sys.stderr.write(__doc__)
        return 1
    split = argv.index("--")
    out_path = argv[1]
    rest = argv[2:split]
    json_paths = argv[split + 1:]

    prefix = ""
    emit_index = True
    while rest[:1] == ["--prefix"] or rest[:1] == ["--no-index"]:
        if rest[0] == "--prefix":
            prefix = rest[1]
            rest = rest[2:]
        else:
            emit_index = False
            rest = rest[1:]
    specs = rest

    if len(specs) != len(json_paths):
        sys.stderr.write(
            f"gen_lang_header: {len(specs)} language specs but {len(json_paths)} catalogs\n")
        return 1

    var_prefix = prefix[:1].lower() + prefix[1:] if prefix else ""
    struct_name = (prefix or "") + "LangCatalog"
    index_var = var_prefix + "LangIndexJson" if var_prefix else "langIndexJson"
    catalogs_var = var_prefix + "LangCatalogs" if var_prefix else "langCatalogs"
    count_var = var_prefix + "LangCatalogCount" if var_prefix else "langCatalogCount"

    index = {}
    entries = []
    for spec, path in zip(specs, json_paths):
        code, _, name = spec.partition("=")
        if emit_index:
            index[code] = name or code
        with open(path, "rb") as fh:
            entries.append((code, fh.read().strip()))

    lines = [
        f"// Generated by scripts/{os.path.basename(__file__)} -- do not edit.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace Controller{",
        f"  struct {struct_name}{{",
        "    const char *code;",
        "    const char *json;",
        "    uint32_t len;",
        "  };",
        "",
    ]

    if emit_index:
        index_json = json.dumps(index, ensure_ascii=False, separators=(",", ":"),
                                 sort_keys=True).encode("utf-8")
        lines += [
            "  /// JSON object mapping every available language code to its native name.",
            f"  static const char *{index_var} =",
            f"    {c_escape(index_json)};",
            f"  static const uint32_t {index_var}Len = {len(index_json)};",
            "",
        ]

    lines.append(f"  static const {struct_name} {catalogs_var}[] = {{")
    if not entries:
        # A zero-sized array is not valid C++; keep a terminator entry instead.
        lines.append('    {0, 0, 0}')
    for code, blob in entries:
        lines.append(f'    {{"{code}",')
        lines.append(f"     {c_escape(blob)},")
        lines.append(f"     {len(blob)}}},")
    lines.append("  };")
    lines.append(f"  static const size_t {count_var} = {len(entries)};")
    lines.append("}")
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
